# Generated by Django 4.2 on 2023-04-30 11:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import penta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('icon', models.FileField(upload_to=penta.models.upload_logo_to, validators=[django.core.validators.FileExtensionValidator(['img', 'png', 'svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('image', models.FileField(upload_to=penta.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['img', 'png', 'svg'])])),
                ('text', models.TextField()),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.FileField(upload_to=penta.models.upload_logo_to, validators=[django.core.validators.FileExtensionValidator(['img', 'png', 'svg'])])),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_lost', models.IntegerField()),
                ('leag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='penta.league')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('leag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='penta.league')),
                ('name1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name1', to='penta.teams')),
                ('name2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name2', to='penta.teams')),
            ],
        ),
    ]
