# Generated by Django 4.2 on 2023-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
