# Generated by Django 4.2 on 2023-04-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_lost', models.IntegerField()),
                ('leag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='penta.league')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('name1', models.CharField(max_length=25)),
                ('name2', models.CharField(max_length=25)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('leag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='penta.league')),
            ],
        ),
    ]
