# Generated by Django 4.2 on 2023-04-29 17:01

from django.db import migrations, models
import penta.models


class Migration(migrations.Migration):

    dependencies = [
        ('penta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=penta.models.upload_to, verbose_name='Image'),
        ),
    ]
