# Generated by Django 4.2 on 2023-04-30 14:49

import django.core.validators
from django.db import migrations, models
import penta.models


class Migration(migrations.Migration):

    dependencies = [
        ('penta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to=penta.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['img', 'png', 'svg', 'jpg'])]),
        ),
    ]
