# Generated by Django 4.2 on 2023-04-29 17:18

from django.db import migrations, models
import penta.models


class Migration(migrations.Migration):

    dependencies = [
        ('penta', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=penta.models.upload_to),
        ),
    ]
