# Generated by Django 4.2 on 2023-04-30 09:47

from django.db import migrations, models
import penta.models


class Migration(migrations.Migration):

    dependencies = [
        ('penta', '0004_teams_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='icon',
            field=models.ImageField(default='', upload_to=penta.models.upload_logo_to),
            preserve_default=False,
        ),
    ]
